# Generated by Django 6.0.6 on 2026-07-13 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_phone_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('manager', 'Menejer'), ('sales', 'Sotuvchi'), ('omborchi', 'Omborchi')], default='sales', max_length=10, verbose_name='Rol'),
        ),
    ]
