# Generated by Django 6.0.6 on 2026-07-25 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_phone_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='opening_production_debt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name="Ochilish ishlab chiqarish qarzi (so'm)"),
        ),
    ]
