# Generated by Django 6.0.6 on 2026-07-13 20:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RawMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nomi')),
                ('sku', models.CharField(blank=True, max_length=50, verbose_name='Artikul (SKU)')),
                ('note', models.TextField(blank=True, verbose_name='Izoh')),
                ('avg_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name="O'rtacha tannarx (1 kg, so'm)")),
                ('low_stock_threshold', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Kam qoldi chegarasi (kg)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Xomashyo',
                'verbose_name_plural': 'Xomashyolar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductionRunItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_kg', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usages', to='manufacturing.rawmaterial')),
            ],
        ),
        migrations.CreateModel(
            name='MaterialPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Sana')),
                ('quantity_kg', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Miqdor (kg)')),
                ('price_per_kg', models.DecimalField(decimal_places=2, max_digits=14, verbose_name="Narx (1 kg, so'm)")),
                ('supplier', models.CharField(blank=True, max_length=200, verbose_name='Yetkazib beruvchi')),
                ('method', models.CharField(choices=[('cash', 'Naqd'), ('card', 'Karta'), ('transfer', "Bank o'tkazmasi")], default='cash', max_length=8, verbose_name="To'lov usuli")),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='material_purchases', to=settings.AUTH_USER_MODEL, verbose_name='Kim kiritdi')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='manufacturing.rawmaterial', verbose_name='Xomashyo')),
            ],
            options={
                'verbose_name': 'Xomashyo xaridi',
                'verbose_name_plural': 'Xomashyo xaridlari',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
