# Generated by Django 6.0.6 on 2026-07-13 20:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0019_employee_expense_employee_attendance'),
        ('manufacturing', '0004_stocktransfer_complete'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerStockEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Sana')),
                ('quantity_kg', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Miqdor (kg, +/−)')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recorded_seller_entries', to=settings.AUTH_USER_MODEL, verbose_name='Kim kiritdi')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='seller_stock_entries', to='crm.product', verbose_name='Mahsulot')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='own_stock_entries', to=settings.AUTH_USER_MODEL, verbose_name='Sotuvchi')),
            ],
            options={
                'verbose_name': 'Sotuvchi ombor harakati',
                'verbose_name_plural': 'Sotuvchi ombor harakatlari',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
