# Generated by Django 6.0.6 on 2026-07-04 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_product_low_stock_threshold_stockentry'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockentry',
            options={'ordering': ['-date', '-created_at'], 'verbose_name': 'Ombor harakati', 'verbose_name_plural': 'Ombor harakatlari'},
        ),
    ]
