# Generated by Django 6.0.6 on 2026-07-04 06:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_alter_stockentry_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Sana')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18, verbose_name="Miqdor (so'm)")),
                ('method', models.CharField(choices=[('cash', 'Naqd'), ('card', 'Karta')], default='cash', max_length=4, verbose_name="To'lov usuli")),
                ('kind', models.CharField(choices=[('sale', "Sotuvda to'langan"), ('debt', "Qarz to'lovi")], max_length=4, verbose_name='Turi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to=settings.AUTH_USER_MODEL, verbose_name='Kim qabul qildi')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='crm.sale', verbose_name='Sotuv')),
            ],
            options={
                'verbose_name': "To'lov",
                'verbose_name_plural': "To'lovlar",
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
