# Generated by Django 6.0.6 on 2026-07-05 11:17

import django.db.models.deletion
from django.db import migrations, models


def copy_sales_to_items(apps, schema_editor):
    """Move each existing single-product Sale row into a SaleItem line."""
    Sale = apps.get_model("crm", "Sale")
    SaleItem = apps.get_model("crm", "SaleItem")
    items = [
        SaleItem(
            sale_id=sale.id,
            product_id=sale.product_id,
            dimension=sale.dimension,
            weight=sale.weight,
            price=sale.price,
            cost_price=sale.cost_price,
        )
        for sale in Sale.objects.all()
    ]
    SaleItem.objects.bulk_create(items)


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_backfill_sale_payments'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dimension', models.CharField(choices=[('kg', 'kg'), ('g', 'g')], default='kg', max_length=2, verbose_name="O'lchov birligi")),
                ('weight', models.DecimalField(decimal_places=3, max_digits=12, verbose_name="Og'irligi")),
                ('price', models.DecimalField(decimal_places=2, max_digits=14, verbose_name="Narxi (1 birlik, so'm)")),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=14, verbose_name="Tannarxi (1 birlik, so'm)")),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_items', to='crm.product', verbose_name='Mahsulot')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='crm.sale', verbose_name='Sotuv')),
            ],
            options={
                'verbose_name': 'Sotuv qatori',
                'verbose_name_plural': 'Sotuv qatorlari',
            },
        ),
        migrations.RunPython(copy_sales_to_items, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='sale',
            name='cost_price',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='dimension',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='price',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='product',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='weight',
        ),
    ]
