# Generated by Django 6.0.6 on 2026-07-05 11:50

from datetime import timedelta

from django.db import migrations, models


def backfill_deadlines(apps, schema_editor):
    """Every sale now carries a deadline; give paid sales (null) date + 7 days."""
    Sale = apps.get_model("crm", "Sale")
    for sale in Sale.objects.filter(debt_deadline__isnull=True):
        sale.debt_deadline = sale.date + timedelta(days=7)
        sale.save(update_fields=["debt_deadline"])


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_split_sale_into_items'),
    ]

    operations = [
        migrations.RunPython(backfill_deadlines, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='sale',
            name='is_debt',
        ),
        migrations.AlterField(
            model_name='sale',
            name='debt_deadline',
            field=models.DateField(blank=True, null=True, verbose_name="To'lov muddati"),
        ),
    ]
