# Generated by Django 6.0.6 on 2026-07-05 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_payment_transfer_commission'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='commission_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Bank ushlagan foiz (%)'),
        ),
        migrations.AddField(
            model_name='payment',
            name='note',
            field=models.CharField(blank=True, max_length=255, verbose_name='Izoh'),
        ),
    ]
