# Generated by Django 6.0.6 on 2026-07-05 18:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_payment_commission_percent_payment_note'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(choices=[('create', "Qo'shildi"), ('update', "O'zgartirildi"), ('delete', "O'chirildi"), ('void', 'Bekor qilindi'), ('payment', "To'lov")], max_length=10, verbose_name='Amal')),
                ('target_type', models.CharField(max_length=40, verbose_name='Obyekt')),
                ('target_id', models.IntegerField(blank=True, null=True, verbose_name='ID')),
                ('summary', models.CharField(max_length=255, verbose_name='Tafsilot')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Kim')),
            ],
            options={
                'verbose_name': 'Audit yozuvi',
                'verbose_name_plural': 'Audit jurnali',
                'ordering': ['-created_at'],
            },
        ),
    ]
