# Generated by Django 6.0.6 on 2026-07-05 18:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0011_auditlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('create', "Qo'shildi"), ('update', "O'zgartirildi"), ('delete', "O'chirildi"), ('void', 'Bekor qilindi'), ('payment', "To'lov"), ('return', 'Qaytarish')], max_length=10, verbose_name='Amal'),
        ),
        migrations.CreateModel(
            name='Return',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dimension', models.CharField(choices=[('kg', 'kg'), ('g', 'g')], default='kg', max_length=2, verbose_name="O'lchov birligi")),
                ('weight', models.DecimalField(decimal_places=3, max_digits=12, verbose_name="Og'irligi")),
                ('price', models.DecimalField(decimal_places=2, max_digits=14, verbose_name="Narxi (1 birlik, so'm)")),
                ('date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Sana')),
                ('restock', models.BooleanField(default=True, verbose_name='Omborga qaytarilsin')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='returns', to=settings.AUTH_USER_MODEL, verbose_name='Kim qabul qildi')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='crm.product', verbose_name='Mahsulot')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='crm.sale', verbose_name='Sotuv')),
            ],
            options={
                'verbose_name': 'Qaytarish',
                'verbose_name_plural': 'Qaytarishlar',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
