# Generated by Django 6.0.6 on 2026-07-07 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0013_expense'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='currency',
            field=models.CharField(choices=[('uzs', "So'm"), ('usd', 'Dollar')], default='uzs', max_length=3, verbose_name='Valyuta'),
        ),
        migrations.AddField(
            model_name='payment',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name="Dollar kursi (1$ = so'm)"),
        ),
    ]
