# Generated by Django 6.0.6 on 2026-07-08 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0015_expense_amount_original_expense_currency_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='email',
        ),
    ]
