# Generated by Django 6.0.6 on 2026-07-08 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0016_remove_client_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('create', "Qo'shildi"), ('update', "O'zgartirildi"), ('delete', "O'chirildi"), ('void', 'Bekor qilindi'), ('payment', "To'lov"), ('return', 'Qaytarish'), ('transfer', "Sotuvchi o'zgartirildi")], max_length=10, verbose_name='Amal'),
        ),
    ]
