# Generated by Django 6.0.6 on 2026-07-11 19:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0017_alter_auditlog_action'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionRemittance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Sana')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18, verbose_name="Summa (so'm)")),
                ('method', models.CharField(choices=[('cash', 'Naqd'), ('card', 'Karta'), ('transfer', "Bank o'tkazmasi")], default='cash', max_length=8, verbose_name="To'lov usuli")),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recorded_remittances', to=settings.AUTH_USER_MODEL, verbose_name='Kim kiritdi')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='remittances', to=settings.AUTH_USER_MODEL, verbose_name='Sotuvchi')),
            ],
            options={
                'verbose_name': 'Ishlab chiqarishga topshiruv',
                'verbose_name_plural': 'Ishlab chiqarishga topshiruvlar',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
