# Generated by Django 6.0.6 on 2026-07-15 14:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0018_productionremittance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Sana')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recorded_receipts', to=settings.AUTH_USER_MODEL, verbose_name='Kim kiritdi')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_receipts', to=settings.AUTH_USER_MODEL, verbose_name='Sotuvchi')),
            ],
            options={
                'verbose_name': 'Ishlab chiqarishdan qabul',
                'verbose_name_plural': 'Ishlab chiqarishdan qabullar',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductionReceiptItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_kg', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Miqdori (kg)')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipt_items', to='crm.product', verbose_name='Mahsulot')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='crm.productionreceipt', verbose_name='Qabul')),
            ],
            options={
                'verbose_name': 'Qabul qatori',
                'verbose_name_plural': 'Qabul qatorlari',
            },
        ),
    ]
