# Generated by Django 6.0.6 on 2026-07-13 16:51

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0018_productionremittance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Ismi')),
                ('salary_type', models.CharField(choices=[('hourly', 'Soatbay (smena)'), ('fixed', 'Fiks oylik')], default='hourly', max_length=6, verbose_name='Ish haqi turi')),
                ('hourly_rate', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name="Soat narxi (so'm)")),
                ('monthly_salary', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name="Oylik summa (so'm)")),
                ('standard_daily_hours', models.DecimalField(decimal_places=2, default=Decimal('11'), max_digits=5, verbose_name='Kunlik standart soat')),
                ('works_shifts', models.BooleanField(default=True, verbose_name='Smena bilan ishlaydi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Xodim',
                'verbose_name_plural': 'Xodimlar',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='expense',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='salary_expenses', to='crm.employee', verbose_name='Xodim (oylik/avans)'),
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Sana')),
                ('hours', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Ishlagan soat')),
                ('shift', models.CharField(blank=True, choices=[('day', 'Kunduzi'), ('night', 'Kechki')], max_length=5, verbose_name='Smena')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='crm.employee', verbose_name='Xodim')),
            ],
            options={
                'verbose_name': 'Davomad',
                'verbose_name_plural': 'Davomad',
                'ordering': ['-date'],
                'constraints': [models.UniqueConstraint(fields=('employee', 'date'), name='uniq_attendance_employee_date')],
            },
        ),
    ]
