# Generated by Django 6.0.6 on 2026-07-16 07:22

import django.db.models.deletion
from django.db import migrations, models
from django.db.models import OuterRef, Subquery


def backfill_fulfilled_at(apps, schema_editor):
    """Every pre-existing sale line was in-stock under the old rules, so mark it
    fulfilled on its sale date."""
    SaleItem = apps.get_model('crm', 'SaleItem')
    Sale = apps.get_model('crm', 'Sale')
    SaleItem.objects.filter(fulfilled_at__isnull=True).update(
        fulfilled_at=Subquery(
            Sale.objects.filter(pk=OuterRef('sale_id')).values('date')[:1]
        )
    )


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0019_productionreceipt_productionreceiptitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='fulfilled_at',
            field=models.DateField(blank=True, null=True, verbose_name='Bajarilgan sana'),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='fulfilled_by_receipt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fulfilled_items', to='crm.productionreceipt', verbose_name='Qabul (biriktirilgan)'),
        ),
        migrations.RunPython(backfill_fulfilled_at, noop),
    ]
