# Generated by Django 6.0.6 on 2026-07-17 09:11

from decimal import Decimal

from django.db import migrations, models
from django.db.models import Case, DecimalField, F, Value, When


def backfill_fulfilled_kg(apps, schema_editor):
    """A line already marked fully fulfilled has its whole weight (in kg) filled."""
    SaleItem = apps.get_model('crm', 'SaleItem')
    SaleItem.objects.filter(fulfilled_at__isnull=False).update(
        fulfilled_kg=Case(
            When(dimension='g', then=F('weight') / Value(Decimal('1000'))),
            default=F('weight'),
            output_field=DecimalField(max_digits=12, decimal_places=3),
        )
    )


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0021_profitpayout'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='fulfilled_kg',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Bajarilgan miqdor (kg)'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='fulfilled_at',
            field=models.DateField(blank=True, null=True, verbose_name="To'liq bajarilgan sana"),
        ),
        migrations.RunPython(backfill_fulfilled_kg, noop),
    ]
