# Generated by Django 6.0.6 on 2026-07-19 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0022_saleitem_fulfilled_kg_alter_saleitem_fulfilled_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='advance_payments', to='crm.client', verbose_name='Mijoz'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='kind',
            field=models.CharField(choices=[('sale', "Sotuvda to'langan"), ('debt', "Qarz to'lovi"), ('advance_in', "Oldindan to'lov (avans)"), ('advance_used', 'Avansdan yechildi')], max_length=12, verbose_name='Turi'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='crm.sale', verbose_name='Sotuv'),
        ),
    ]
