# Return now points at the exact sale line it reverses, and carries the tannarx of
# the returned goods. Written by hand rather than autogenerated: `sale_item` is a
# non-null FK, and the autodetector insists on a one-off default even though the
# crm_return table is empty, which would leave a meaningless default=1 in the file.

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0023_payment_client_alter_payment_kind_alter_payment_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='return',
            name='sale_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='crm.saleitem', verbose_name='Sotuv qatori'),
        ),
        migrations.AddField(
            model_name='return',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name="Tannarxi (1 birlik, so'm)"),
        ),
        migrations.AlterField(
            model_name='payment',
            name='kind',
            field=models.CharField(choices=[('sale', "Sotuvda to'langan"), ('debt', "Qarz to'lovi"), ('advance_in', "Oldindan to'lov (avans)"), ('advance_used', 'Avansdan yechildi'), ('return_credit', 'Qaytarishdan kredit'), ('refund_out', 'Qaytarish (naqd berildi)')], max_length=16, verbose_name='Turi'),
        ),
    ]
