# Generated by Django 6.0.6 on 2026-07-20 17:34

import django.db.models.deletion
from django.db import migrations, models

PREFIX = "Qaytarish: "


def link_settlements(apps, schema_editor):
    """Reconnect each existing return-settlement payment (a cash refund or an advance
    credit) to the return that produced it, so returns made before this link existed
    can still be voided cleanly. Match on sale + product (from the payment note), taking
    each return only once; fall back to sale-only when the product name has since changed."""
    Return = apps.get_model("crm", "Return")
    Payment = apps.get_model("crm", "Payment")
    for p in Payment.objects.filter(
        kind__in=["refund_out", "return_credit"]
    ).order_by("created_at", "id"):
        note = p.note or ""
        prod_name = note[len(PREFIX):].strip() if note.startswith(PREFIX) else None
        ret = None
        if prod_name:
            ret = (
                Return.objects.filter(
                    sale_id=p.sale_id, settlement__isnull=True, product__name=prod_name
                )
                .order_by("created_at", "id")
                .first()
            )
        if ret is None:
            ret = (
                Return.objects.filter(sale_id=p.sale_id, settlement__isnull=True)
                .order_by("created_at", "id")
                .first()
            )
        if ret is not None:
            ret.settlement_id = p.id
            ret.save(update_fields=["settlement"])


def unlink_settlements(apps, schema_editor):
    Return = apps.get_model("crm", "Return")
    Return.objects.update(settlement=None)


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0024_return_sale_item_return_cost_price_alter_payment_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='return',
            name='settlement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settled_return', to='crm.payment', verbose_name="Hisob-kitob to'lovi"),
        ),
        migrations.RunPython(link_settlements, unlink_settlements),
    ]
