# Generated by Django 6.0.6 on 2026-07-24 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0025_return_settlement'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='has_micron',
            field=models.BooleanField(default=False, verbose_name='Mikron bor'),
        ),
        migrations.AddField(
            model_name='product',
            name='has_size',
            field=models.BooleanField(default=False, verbose_name='Razmer bor'),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='micron',
            field=models.CharField(blank=True, choices=[('015', '015'), ('01', '01'), ('08', '08'), ('06', '06'), ('05', '05'), ('04', '04'), ('03', '03'), ('02', '02')], max_length=8, verbose_name='Mikron'),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='size',
            field=models.CharField(blank=True, choices=[('1,5м', '1,5м'), ('2м', '2м'), ('6м', '6м')], max_length=8, verbose_name='Razmer'),
        ),
    ]
