# Generated by Django 6.0.6 on 2026-07-24 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0026_product_has_micron_product_has_size_saleitem_micron_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='is_opening',
            field=models.BooleanField(default=False, verbose_name="Ochilish qoldig'i"),
        ),
        migrations.AddField(
            model_name='sale',
            name='opening_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name="Ochilish qarzi (so'm)"),
        ),
    ]
