# Generated by Django 6.0.6 on 2026-07-24 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0027_sale_is_opening_sale_opening_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='is_opening',
            field=models.BooleanField(default=False, verbose_name='Ochilish avansi'),
        ),
    ]
