# Generated by Django 6.0.6 on 2026-07-28 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0028_payment_is_opening'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleitem',
            name='micron',
            field=models.CharField(blank=True, max_length=20, verbose_name='Mikron'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='size',
            field=models.CharField(blank=True, max_length=20, verbose_name='Razmer'),
        ),
    ]
