# Generated by Django 6.0.6 on 2026-07-29 12:28

from django.db import migrations, models

# `category` used to be a coded choice field; it is free text now, so the stored
# codes have to become the labels people already saw in the UI — otherwise every
# old expense would suddenly read "fuel" instead of "Benzin / transport".
CODE_TO_LABEL = {
    "fuel": "Benzin / transport",
    "salary": "Oylik / xodim",
    "rent": "Ijara",
    "meal": "Ovqat (obed)",
    "purchase": "Mahsulot xaridi",
    "other": "Boshqa",
}


def codes_to_labels(apps, schema_editor):
    Expense = apps.get_model("crm", "Expense")
    for code, label in CODE_TO_LABEL.items():
        Expense.objects.filter(category=code).update(category=label)


def labels_to_codes(apps, schema_editor):
    Expense = apps.get_model("crm", "Expense")
    for code, label in CODE_TO_LABEL.items():
        Expense.objects.filter(category=label).update(category=code)
    # Anything typed by hand has no code to go back to; park it in "other" so the
    # old choice field still validates.
    Expense.objects.exclude(category__in=CODE_TO_LABEL).update(category="other")


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0029_alter_saleitem_micron_alter_saleitem_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(max_length=40, verbose_name='Turkum'),
        ),
        migrations.RunPython(codes_to_labels, labels_to_codes),
    ]
