# Generated by Django 6.0.6 on 2026-08-01 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0031_employee_and_expense_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='commission_payer',
            field=models.CharField(choices=[('seller', 'Sotuvchidan ushlansin'), ('client', 'Mijozdan ushlansin')], default='seller', max_length=6, verbose_name="Komissiyani kim ko'taradi"),
        ),
    ]
