# Generated by Django 6.0.6 on 2026-08-01 16:03

from django.db import migrations, models


def clear_flag_where_nobody_is_tagged(apps, schema_editor):
    """The field defaults to True so every existing wage/advance keeps counting against
    its month — the behaviour the books were written under. On rows with no worker the
    flag means nothing, so it is cleared: that way "True" always reads as a real claim
    on someone's pay, and a later edit that picks a worker starts from a clean answer."""
    Expense = apps.get_model('crm', 'Expense')
    Expense.objects.filter(employee__isnull=True).update(counts_against_salary=False)


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0032_payment_commission_payer'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='counts_against_salary',
            field=models.BooleanField(default=True, verbose_name='Oyligidan ushlansin'),
        ),
        migrations.RunPython(
            clear_flag_where_nobody_is_tagged,
            migrations.RunPython.noop,
        ),
    ]
