# Generated by Django 6.0.6 on 2026-08-08 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0033_expense_counts_against_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='kind',
            field=models.CharField(choices=[('sale', "Sotuvda to'langan"), ('debt', "Qarz to'lovi"), ('advance_in', "Oldindan to'lov (avans)"), ('advance_used', 'Avansdan yechildi'), ('return_credit', 'Qaytarishdan kredit'), ('refund_out', 'Qaytarish (naqd berildi)'), ('adjust_credit', 'Narx tuzatildi (kreditga)'), ('adjust_refund', 'Narx tuzatildi (naqd berildi)')], max_length=16, verbose_name='Turi'),
        ),
    ]
