# Generated by Django 6.0.6 on 2026-08-08 11:37

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0034_payment_adjust_kinds'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Sana')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18, verbose_name="Summa (so'm)")),
                ('reason', models.CharField(choices=[('ledger', 'Eski daftar/sverka xato edi'), ('remittance', 'Topshirilgan pul kiritilmagan'), ('sale', 'Sotuv kiritilmagan'), ('other', 'Boshqa')], max_length=12, verbose_name='Sababi')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recorded_production_adjustments', to=settings.AUTH_USER_MODEL, verbose_name='Kim kiritdi')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_adjustments', to=settings.AUTH_USER_MODEL, verbose_name='Sotuvchi')),
            ],
            options={
                'verbose_name': 'Ishlab chiqarish qarzi tuzatishi',
                'verbose_name_plural': 'Ishlab chiqarish qarzi tuzatishlari',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
