# Generated by Django 6.0.6 on 2026-08-15 12:20

import crm.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0036_payment_advance_out'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='end_month',
            field=models.DateField(blank=True, null=True, verbose_name='Oxirgi oy'),
        ),
        migrations.AddField(
            model_name='employee',
            name='opening_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name="Boshlang'ich qoldiq (so'm)"),
        ),
        migrations.AddField(
            model_name='employee',
            name='start_month',
            field=models.DateField(default=crm.models.first_of_month, verbose_name='Hisob boshlangan oy'),
        ),
        migrations.CreateModel(
            name='SalaryRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_from', models.DateField(verbose_name='Qaysi oydan')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18, verbose_name="Oylik (so'm)")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='salary_rates', to=settings.AUTH_USER_MODEL, verbose_name='Kim belgiladi')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='crm.employee', verbose_name='Xodim')),
            ],
            options={
                'verbose_name': 'Oylik stavkasi',
                'verbose_name_plural': 'Oylik stavkalari',
                'ordering': ['-effective_from', '-pk'],
                'constraints': [models.UniqueConstraint(fields=('employee', 'effective_from'), name='one_rate_per_month')],
            },
        ),
    ]
