# Generated by Django 6.0.6 on 2026-09-05 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0038_seed_salary_rates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(max_length=120, verbose_name='Turkum'),
        ),
    ]
