# Generated by Django 6.0.6 on 2026-09-13 12:14

from django.db import migrations, models


def carry_over_terms(apps, schema_editor):
    """Give every existing receipt the term its own dates were written with.

    Until now the deadline was the only thing stored, so the term was whatever gap
    the seller typed at the time. From here the term is the stored fact and the
    deadline is derived from it, so it has to be read out of the old rows once —
    otherwise the first payment on an old debt would restart a term of zero days.
    Receipts with no deadline (nothing was agreed) are left alone: `Sale.term_days`
    falls back to the default for them.
    """
    Sale = apps.get_model("crm", "Sale")
    for pk, sale_date, deadline in Sale.objects.filter(
        debt_deadline__isnull=False, debt_term_days__isnull=True
    ).values_list("pk", "date", "debt_deadline"):
        Sale.objects.filter(pk=pk).update(
            debt_term_days=max((deadline - sale_date).days, 0)
        )


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0039_alter_expense_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='debt_term_days',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Qarz muddati (kun)'),
        ),
        migrations.RunPython(carry_over_terms, migrations.RunPython.noop),
    ]
