# Generated by Django 6.0.6 on 2026-09-29 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0042_client_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='rolls',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Rulon soni'),
        ),
    ]
