# Generated by Django 6.0.6 on 2026-10-01 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0043_saleitem_rolls'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='note',
            field=models.CharField(blank=True, max_length=255, verbose_name='Izoh'),
        ),
    ]
