# Generated by Django 6.0.6 on 2026-10-04 12:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0044_sale_note'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='Sana')),
                ('name', models.CharField(max_length=80, verbose_name='Nomi')),
                ('rest', models.BooleanField(default=True, verbose_name='Dam beriladi')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='holidays', to=settings.AUTH_USER_MODEL, verbose_name='Kim kiritdi')),
            ],
            options={
                'verbose_name': 'Bayram',
                'verbose_name_plural': 'Bayramlar',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Sana')),
                ('present', models.BooleanField(default=True, verbose_name='Keldi')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attendance_entries', to=settings.AUTH_USER_MODEL, verbose_name='Kim kiritdi')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='crm.employee', verbose_name='Xodim')),
            ],
            options={
                'verbose_name': 'Davomad',
                'verbose_name_plural': 'Davomad',
                'ordering': ['-date', 'employee__name'],
                'constraints': [models.UniqueConstraint(fields=('employee', 'date'), name='one_attendance_row_per_day')],
            },
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Sana')),
                ('paid', models.BooleanField(default=False, verbose_name='Oyligi saqlanadi')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='granted_leaves', to=settings.AUTH_USER_MODEL, verbose_name='Kim belgiladi')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaves', to='crm.employee', verbose_name='Xodim')),
            ],
            options={
                'verbose_name': 'Rejalashtirilgan dam',
                'verbose_name_plural': 'Rejalashtirilgan damlar',
                'ordering': ['-date', 'employee__name'],
                'constraints': [models.UniqueConstraint(fields=('employee', 'date'), name='one_leave_per_day')],
            },
        ),
    ]
