# Generated by Django 6.0.6 on 2026-10-05 17:21

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0046_seed_holidays'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='work_end',
            field=models.TimeField(blank=True, default=datetime.time(19, 0), null=True, verbose_name='Ish tugashi'),
        ),
        migrations.AddField(
            model_name='employee',
            name='work_start',
            field=models.TimeField(blank=True, default=datetime.time(9, 0), null=True, verbose_name='Ish boshlanishi'),
        ),
        migrations.CreateModel(
            name='DayHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Sana')),
                ('start', models.TimeField(verbose_name='Ish boshlanishi')),
                ('end', models.TimeField(verbose_name='Ish tugashi')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='day_hours_set', to=settings.AUTH_USER_MODEL, verbose_name='Kim belgiladi')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_hours', to='crm.employee', verbose_name='Xodim')),
            ],
            options={
                'verbose_name': 'Kunlik ish vaqti',
                'verbose_name_plural': 'Kunlik ish vaqtlari',
                'ordering': ['-date', 'employee__name'],
                'constraints': [models.UniqueConstraint(fields=('employee', 'date'), name='one_hours_row_per_day')],
            },
        ),
    ]
